# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 00:30
from __future__ import unicode_literals

from django.db import migrations
import csv


def add_data1(apps, schema_editor):
    Rating = apps.get_model("movie_rating_relations", "Rating")
    Rater = apps.get_model("movie_rating_relations", "Rater")
    Movie = apps.get_model("movie_rating_relations", "Movie")
    with open("data") as infile:
        read_file = csv.reader(infile, delimiter='\t')
        for row in read_file:
            rater_user_id = Rater.objects.get(Rater.user_id)
            movie_movie_id = Movie.objects.get(Movie.movie_id)
            Rating.objects.create(user_id=rater_user_id, item_id=movie_movie_id, rating=row[2], time_stamp=row[3])
    raise Exception("yay")


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rating_relations', '0002_auto_20160607_2204'),
    ]

    operations = [
    ]
