# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 17:10
from __future__ import unicode_literals

from django.db import migrations
import csv


def add_rating_data(apps, schema_editor):
    Rater = apps.get_model("movie_rating_relations", "Rater")
    Movie = apps.get_model("movie_rating_relations", "Movie")
    Rating = apps.get_model("movie_rating_relations", "Rating")
    with open("data") as infile:
        read_file = csv.reader(infile, delimiter='\t')
        for row in read_file:
            rater_user_id = Rater.objects.get(user_id=row[0])
            movie_movie_id = Movie.objects.get(movie_id=row[1])
            Rating.objects.create(user_id=rater_user_id, item_id=movie_movie_id, rating=row[2], time_stamp=row[3])


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rating_relations', '0003_auto_20160608_1709'),
    ]

    operations = [
        migrations.RunPython(add_rating_data)
    ]
